namespace SyncNet.Api.Entities;

/// <summary>
/// Base class for all syncable entities following WatermelonDB protocol.
/// </summary>
public abstract class SyncableEntity
{
    /// <summary>
    /// Unique identifier generated by the client (UUID).
    /// </summary>
    public string Id { get; set; } = null!;

    /// <summary>
    /// Unix timestamp in milliseconds when the record was created.
    /// </summary>
    public long CreatedAt { get; set; }

    /// <summary>
    /// Unix timestamp in milliseconds when the record was last modified.
    /// Maps to 'last_modified' in WatermelonDB protocol.
    /// </summary>
    public long UpdatedAt { get; set; }

    /// <summary>
    /// Soft delete flag. When true, the record is considered deleted.
    /// </summary>
    public bool IsDeleted { get; set; }
}
